In [1]:
import numpy
from numpy import array
from sklearn.model_selection import KFold#for kfold cross validation

data1 = array([0.1,0.2,0.3,0.4,0.5,0.6])
kfold1 = KFold(3)
print(kfold1)

KFold(n_splits=3, random_state=None, shuffle=False)


In [2]:
for train,test in kfold1.split(data1):
    print(train)
    print(test)

[2 3 4 5]
[0 1]
[0 1 4 5]
[2 3]
[0 1 2 3]
[4 5]


In [3]:
print('training data: %s, test data: %s' %(data1[train],data1[test]))

training data: [0.1 0.2 0.3 0.4], test data: [0.5 0.6]


In [4]:
#for bootstrapping
from sklearn.utils import resample
btrap1 = resample(data1, replace= True, n_samples=4, random_state=1)
print('Bootstrap sample : %s' %btrap1)

Bootstrap sample : [0.6 0.4 0.5 0.1]


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv('Social_Network_Ads.csv')
print(dataset)

X= dataset.iloc[:,[1,2,3]].values
Y= dataset.iloc[:,-1].values


##print(X)
##print(Y)
##add your code here to convert gender as a numerical variable without using any function##


index = 0
for i in X[:,0]:
    if i == 'Male':
        X[index,0] = 1
    else:
        X[index,0] = 0
    index = index + 1
print(X[:,0])    
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.20, random_state=1)

## standardization of data##
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)

print(X_train)


      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]
[1 1 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0
 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0
 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 0 0
 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 0